const clearBtn = document.querySelector('#clear'); 
clearBtn.addEventListener('click', () => numberResult.textContent = '');
clearBtn.addEventListener('click', () => slideContainer.textContent = '');
clearBtn.addEventListener('click', () => admitted.textContent = '');
clearBtn.addEventListener('click', () => refused.textContent = '');
clearBtn.addEventListener('click', () => output.textContent = '');
clearBtn.addEventListener('click', () => output.textContent = '');
clearBtn.addEventListener('click', () => section.textContent = '');
clearBtn.addEventListener('click', () => catResult.textContent = '');
clearBtn.addEventListener('click', () => primeResult.textContent = '');